language: c

git:
    depth: false

compiler:
    - gcc

services:
    - docker

before_install:
    - docker pull epitechcontent/epitest-docker

stages:
   - build
   - test
   - deploy

notifications:
  email:
    on_success: never
    on_failure: always

jobs:
  include:
      - stage: build
        name: "Build"
        script:
          - docker run -v `pwd`:/project epitechcontent/epitest-docker bash -c "cd project && make re"

      - stage: test
        name: "Test"
          script:
            - docker run -v `pwd`:/project epitechcontent/epitest-docker bash -c "cd project && make tests_run"

      - stage: deploy
        name: "Deployement Epitech Repo"
        if: branch IN (master, travis) AND type != cron AND type != pull_request
        before_script:
          - ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
          - git checkout $TRAVIS_BRANCH
        script:
          - git push --repo=git@git.epitech.eu:/joseph.vidal@epitech.eu/ASM_minilibc_2019 --force