language: c

git:
  depth: false

compiler:
  - gcc

services:
  - docker

before_install:
  - docker pull epitechcontent/epitest-docker

stages:
  - build
  - test

notifications:
  email:
    on_success: never
    on_failure: always

jobs:
  include:
    - stage: build
      name: "Build"
      script:
        - docker run -v $PWD:/project epitechcontent/epitest-docker bash -c "cd project && make re"

    - stage: test
      name: "Test"
      script:
        - docker run -v $PWD:/project epitechcontent/epitest-docker bash -c "cd project && make tests_run"